query EditClientGroupDialog_clientGroups($clientGroupId: ID!) {
  clientGroups(clientGroupIds: [$clientGroupId]) {
    id
    name
    clients {
      id
      user {
        id
        firstName
        lastName
      }
    }
  }
}

query EditClientGroupDialog_clients {
  clients {
    pagination {
      page
      pageSize
    }
    data {
      id
      user {
        id
        firstName
        lastName
      }
    }
  }
}

mutation EditClientGroupDialog_editClientGroup(
  $clientGroupId: ID!
  $userIds: [ID!]
  $name: String
) {
  editClientGroup(clientGroupId: $clientGroupId, userIds: $userIds, name: $name) {
    id
  }
}
