mutation EnhanceAchievementDialog_generateOneJobAchievement($workPositionId: ID!, $index: Int!, $keywords: [String!]) {
  generateOneJobAchievement(workPositionId: $workPositionId, index: $index, keywords: $keywords)
}