query NewApplicationDialog_resumes {
  resumes(archived: false) {
    id
    name
  }
}

mutation NewApplicationDialog_createUsersJob(
  $applicationInstructions: String
  $contact: ContactsInputObject
  $isRemote: Boolean
  $jobDetails: String
  $location: String
  $notes: String
  $payPeriod: UsersJobsPayPeriodEnum
  $position: String!
  $salaryMax: Int
  $salaryMin: Int
  $status: UsersJobsStatusEnum
  $rejectedStage: UsersJobsRejectedStageEnum
  $interviewStep: UsersJobsInterviewStepEnum
  $companyName: String!
  $url: String
  $resumeId: ID
) {
  createUsersJob(
    applicationInstructions: $applicationInstructions
    contact: $contact
    isRemote: $isRemote
    jobDetails: $jobDetails
    location: $location
    notes: $notes
    payPeriod: $payPeriod
    position: $position
    salaryMax: $salaryMax
    salaryMin: $salaryMin
    status: $status
    companyName: $companyName
    url: $url
    rejectedStage: $rejectedStage
    interviewStep: $interviewStep
    resumeId: $resumeId
  ) {
    id
    status
  }
}

query NewApplicationsDialog_usersJobs($id: ID!) {
  usersJobs(usersJobIds: [$id]) {
    id
    status
    isRemote
    jobDetails
    location
    notes
    position
    salaryMax
    salaryMin
    companyName
    url
    rejectedStage
    interviewStep
    payPeriod
    applicationInstructions
  }
}

mutation NewApplicationsDialog_updateUsersJob(
  $id: ID!
  $isRemote: Boolean
  $jobDetails: String
  $location: String
  $notes: String
  $position: String!
  $salaryMax: Int
  $salaryMin: Int
  $status: UsersJobsStatusEnum
  $rejectedStage: UsersJobsRejectedStageEnum
  $interviewStep: UsersJobsInterviewStepEnum
  $companyName: String!
  $url: String
  $resumeId: ID
  $payPeriod: UsersJobsPayPeriodEnum
  $applicationInstructions: String
) {
  updateUsersJob(
    id: $id
    isRemote: $isRemote
    jobDetails: $jobDetails
    location: $location
    notes: $notes
    position: $position
    salaryMax: $salaryMax
    salaryMin: $salaryMin
    status: $status
    rejectedStage: $rejectedStage
    interviewStep: $interviewStep
    companyName: $companyName
    url: $url
    resumeId: $resumeId
    payPeriod: $payPeriod
    applicationInstructions: $applicationInstructions
  ) {
    id
    status
  }
}
