query NewCoverLetterDialog_usersJobs($usersJobIds: [ID!], $archived: Boolean!) {
  usersJobs(usersJobIds: $usersJobIds, archived: $archived) {
    id
    position
    companyName
    coverLetter {
      id
    }
  }
}

query NewCoverLetterDialog_resumes {
  resumes(archived: false) {
    id
    name
  }
}

mutation NewCoverLetterDialog_createUsersJob(
  $position: String!
  $status: UsersJobsStatusEnum
  $companyName: String!
  $jobDetails: String
) {
  createUsersJob(
    position: $position
    status: $status
    companyName: $companyName
    jobDetails: $jobDetails
  ) {
    id
    ...UsersJobs
  }
}

mutation NewCoverLetterDialog_coverLetterUpsert(
  $usersJobId: ID!
  $attributes: UsersJobsCoverLetterInputObject!
) {
  coverLetterUpsert(usersJobId: $usersJobId, attributes: $attributes) {
    id
    ...CoverLetter
  }
}
