mutation NewPageCheckDialog_createPageCheck($url: String!, $checkInterval: PageCheckIntervalEnum!, $resultType: PageCheckResultTypeEnum!, $pageCheckType: PageCheckTypeEnum!, $prompt: String, $multiplePages: Boolean!) {
  createPageCheck(url: $url, checkInterval: $checkInterval, resultType: $resultType, pageCheckType: $pageCheckType, prompt: $prompt, multiplePages: $multiplePages) {
    id
  }
}