mutation TailorResumeDialog_createUsersJob(
  $position: String!
  $status: UsersJobsStatusEnum
  $companyName: String!
  $jobDetails: String
) {
  createUsersJob(
    position: $position
    status: $status
    companyName: $companyName
    jobDetails: $jobDetails
  ) {
    id
    ...UsersJobs
  }
}

mutation TailorResumeDialog_optimizeResumeForJob(
  $keywords: [String!]
  $resumeId: ID!
  $skills: [String!]
  $usersJobId: ID!
) {
  optimizeResumeForJob(
    keywords: $keywords
    resumeId: $resumeId
    skills: $skills
    usersJobId: $usersJobId
  ) {
    id
    ...Resumes
  }
}

mutation TailorResumeDialog_fetchJobKeywords($usersJobId: ID!) {
  fetchJobKeywords(usersJobId: $usersJobId)
}

mutation TailorResumeDialog_fetchMissingSkillsOfJobResume($usersJobId: ID!, $resumeId: ID!) {
  fetchMissingSkillsOfJobResume(usersJobId: $usersJobId, resumeId: $resumeId)
}
