query Chat_getChat($chatId: [ID!]) {
  chats(chatIds: $chatId) {
    id
    status
    messages {
      fromUser
      message
      chatMessageSources {
        score
        document {
          name 
          url
        }
      }
    }
  }
}

subscription ChatSubscription {
  chat {
    content
    chatId
    initial
    requestId
    i
    final
  }
}

mutation Chat_addMessage($chatId: String!, $message: String!) {
  chatAddMessage(chatId: $chatId, message: $message) {
    id
    status
    messages {
      fromUser
      message
    }
  }
}
