fragment CoverLetter on UsersJobsCoverLetterType {
  id
  firstName
  lastName
  email
  candidateAddress
  companyName
  companyLocation
  phoneNumber
  body
  footer
  archived
  mostRecentUsedResumeForGenerate {
    id
  }
}

query CoverLetterContent_coverLetters($coverLetterId: ID!) {
  coverLetters(coverLetterIds: [$coverLetterId]) {
    id
    ...CoverLetter
    usersJob {
      id
      ...UsersJobs
    }
  }
}

query CoverLettercontent_resumes {
  resumes(archived: false) {
    id
    name
  }
}

mutation CoverLetterContent_generateCoverLetter(
  $coverLetterLength: CoverLetterLengthEnum
  $coverLetterTone: CoverLetterToneEnum
  $resumeId: ID!
  $usersJobId: ID!
) {
  generateCoverLetter(
    coverLetterLength: $coverLetterLength
    coverLetterTone: $coverLetterTone
    resumeId: $resumeId
    usersJobId: $usersJobId
  ) {
    id
    body
  }
}

mutation CoverLetterContent_coverLetterUpsert(
  $usersJobId: ID!
  $attributes: UsersJobsCoverLetterInputObject!
) {
  coverLetterUpsert(usersJobId: $usersJobId, attributes: $attributes) {
    id
    ...CoverLetter
  }
}
