query JobPostingsList_jobPostings(
  $page: Int
  $perPage: Int
  $searchTerm: String
  $archived: Boolean
  $sortBy: JobPostingSortEnum
  $sortByDirection: SortByDirectionEnum
) {
  paginatedUsersJobs(
    page: $page
    perPage: $perPage
    searchTerm: $searchTerm
    archived: $archived
    sortBy: $sortBy
    sortByDirection: $sortByDirection
  ) {
    pagination {
      page
      totalPages
    }
    data {
      id
      archived
      clientsShared {
        id
        firstName
        lastName
      }
      companyName
      createdAt
      numClientsApplied
      numClientsShared
      position
      location
      isRemote
      url
      payPeriod
      salaryMin
      salaryMax
    }
  }
}

mutation JobPostingsList_updateUsersJobArchived($id: ID!, $archived: Boolean) {
  updateUsersJob(id: $id, archived: $archived) {
    id
    archived
  }
}
