fragment Interviews_interview on Interview {
  id
  status
  interviewType
  score
  jobTitle
  messages {
    fromUser
    message
  }
}

query Interviews_interviews {
  interviews {
    id
    status
    interviewType
    score
    jobTitle
  }
}


mutation Interviews_interviewAddMessage($interviewId: String!, $message: String!) {
  interviewAddMessage(interviewId: $interviewId, message: $message) {
    ...Interviews_interview
  }
}
