query Applications_usersJobs($archived: Boolean!) {
  usersJobs(archived: $archived) {
    id
    ...UsersJobs
  }
}

mutation Applications_updateUsersJobStatus($id: ID!, $status: UsersJobsStatusEnum!) {
  updateUsersJob(id: $id, status: $status) {
    id
    __typename
    ...UsersJobs
  }
}

mutation Applications_updateUsersJob($id: ID!, $archived: Boolean, $status: UsersJobsStatusEnum) {
  updateUsersJob(id: $id, archived: $archived, status: $status) {
    id
    __typename
    ...UsersJobs
  }
}
