fragment Users on Users {
  id
  uniqueId
  role
  email
  firstName
  lastName
  plan
  tokenCoverLetter
  tokenInterviewQuestions
  tokenJobMatch
  tokenProfessionalSummary
  tokenSalaryInsights
  tokenLearnSkills
  tokenAchievements
  tokenInterview
  usedChromeExtension
  numUploadedResumes
  numStartedInterviews
  referralTokens
  hasSubscription
  isAdvisoryClient
  isAdvisoryOrgAccount
}

query useCurrentUser_users {
  user {
    id
    ...Users
  }
}
