fragment Users on Users {
  id
  email
  firstName
  lastName
  business {
    id
    name
    plan
    reachedFreePlanPageCheckLimit
    reachedManuallyRunLimit
    numPageChecks
  }
}

query useCurrentUser_users {
  user {
    id
    ...Users
  }
}
