query ResetPassword_resetPasswordAllowed($resetPasswordToken: String!) {
  resetPasswordAllowed(resetPasswordToken: $resetPasswordToken)
}

mutation ResetPassword_resetPassword($resetPasswordToken: String!, $newPassword: String!) {
  authResetPassword(resetPasswordToken: $resetPasswordToken, newPassword: $newPassword)
}
