query ApplicationToolbar_usersJobsArchived($usersJobIds: [ID!]) {
  usersJobs(usersJobIds: $usersJobIds) {
    id
    archived
  }
}

mutation ApplicationToolbar_updateUsersJobArchive($id: ID!, $archive: Boolean) {
  updateUsersJob(id: $id, archived: $archive) {
    id
    archived
  }
}
