query ClientsToolbar_advisors {
  advisors(page: 1, perPage: 999999) {
    pagination {
      page
      totalPages
    }
    data {
      id
      user {
        id
        firstName
        lastName
      }
    }
  }
}
