fragment ResumesList_resumes on Resumes {
  id
  name
  archived
  createdAt
  updatedAt
  aiGenerated
}

query ResumesList_allResumes {
  resumes {
    id
    name
  }
}

query ResumesList_resumes($archived: Boolean, $aiGenerated: Boolean) {
  resumes(archived: $archived, aiGenerated: $aiGenerated) {
    id
    ...ResumesList_resumes
  }
}

mutation ResumeList_updateArchivedResume($id: ID!, $archived: Boolean!) {
  updateArchivedResume(id: $id, archived: $archived) {
    ...ResumesList_resumes
  }
}

mutation ResumeList_duplicateResume($id: ID!) {
  duplicateResume(id: $id) {
    ...ResumesList_resumes
  }
}
