query PageCheck_getPageCheck($pageCheckIds: [ID!]) {
  pageChecks(pageCheckIds: $pageCheckIds) {
    id
    pageUrl
    pageCheckType
    checkInterval
    resultType
    prompt
    keywordFilter
    jobLocationFilter
    jobDepartmentFilter
    priceMinAllowed
    priceDiscrepancyThresholdAmount
    multiplePages
    pageCheckResults {
      id
      createdAt
      result
      sameResultAsLastRun
    }
  }
}

mutation PageCheck_manuallyRunPageCheck($id: ID!) {
  manuallyRunPageCheck(pageCheckId: $id) {
    id
    pageUrl
    checkInterval
    resultType
    prompt
    pageCheckResults {
      id
      createdAt
      result
      sameResultAsLastRun
    }
  }
}